//! The prost approach: the de-facto Rust protobuf stack (`prost` + `prost-build`).
//!
//! prost generates plain structs with a `#[derive(prost::Message)]` and round-trips them
//! through the `bytes`-based `Message::encode_to_vec` / `Message::decode`. The generated
//! types live in [`generated`] (committed, regenerated by `benches/proto-gen`). Because
//! protobuf is tag-value with length prefixes only on embedded messages - not strict KLV -
//! and has no `u8`/`u16`/`i16` types, the schema widens those to `uint32`/`sint32` and the
//! [`flat`] / [`nested`] wrappers narrow back on decode.
//!
//! protobuf has no native framing, so this approach inherits the shared seek-based
//! `encode_framed` / `decode_framed` defaults (overriding neither), exactly like the manual,
//! serde_klv, and tlv_parser approaches.
//!
//! Measurement note: the generated message is built field-by-field from the KLV record
//! *inside* the timed `encode`, so these bars measure "KLV record -> proto message map +
//! serialize", not pure serialization - the map cost is part of the comparison.
//!
//! Author: aav
// --------------------------------------------------
// mods
// --------------------------------------------------
mod compound;
#[rustfmt::skip]
mod generated;
mod rich;
mod simple;

// --------------------------------------------------
// local
// --------------------------------------------------
use crate::suite::Approach;

/// The prost approach.
pub(crate) struct Prost;

/// [`Prost`] implementation of [`Approach`]
impl Approach for Prost {
    const NAME: &'static str = "prost";
}
