//! The quick-protobuf approach: a minimal-allocation reader/writer protobuf stack, generated
//! by the `pb-rs` library.
//!
//! quick-protobuf decodes by borrowing from the input slice and encodes through a `Writer`
//! over any `std::io::Write` sink. The generated types live in [`generated`] (committed,
//! regenerated by `benches/proto-gen`); `pb-rs` emits one file per `.proto`, so they are
//! stitched into inline modules there, and `dont_use_cow` is set so the messages own their
//! data.
//!
//! Invariant: the benchmark messages have no `string` / `bytes` fields, so `from_reader`
//! returns a fully owned value and no borrow of the input slice leaks into [`Codec`]'s
//! `decode(&[u8]) -> Option<R>`. Adding such a field later would break this and force a
//! lifetime onto the codec - so it must trip a reviewer.
//!
//! As with the other protobuf approaches, the KLV `u8`/`u16`/`i16` widths widen to
//! `uint32`/`sint32` and the [`flat`] / [`nested`] wrappers narrow back on decode; framing
//! uses the inherited shared seek defaults; and the proto-message build is inside the timed
//! `encode`.
//!
//! Author: aav
// --------------------------------------------------
// mods
// --------------------------------------------------
mod flat;
mod generated;
mod native;
mod nested;

// --------------------------------------------------
// local
// --------------------------------------------------
use crate::suite::Approach;

/// The quick-protobuf approach.
pub(crate) struct QuickProtobuf;

/// [`QuickProtobuf`] implementation of [`Approach`]
impl Approach for QuickProtobuf {
    const NAME: &'static str = "quick_protobuf";
}
