//! The micropb approach: a `no_std`-first protobuf stack aimed at embedded targets, generated
//! by `micropb-gen`.
//!
//! micropb generates messages over configurable container types and encodes/decodes through
//! its own `PbEncoder` / `PbDecoder` (no `bytes`, no reflection). Here it is generated with
//! the **alloc** container config, so `repeated` fields decode into `Vec` - matching the
//! other approaches' `Vec<Reading>`. The generated types live in [`generated`] (committed,
//! regenerated by `benches/proto-gen`) under a `bench_` package module; presence of message
//! fields (the embedded coordinate) is tracked in a `_has` hazzer, so the coordinate is set
//! via the generated `set_coord` builder rather than a struct field.
//!
//! As with the other protobuf approaches, the KLV `u8`/`u16`/`i16` widths widen to
//! `uint32`/`sint32` and the [`flat`] / [`nested`] wrappers narrow back on decode; framing
//! uses the inherited shared seek defaults; and the proto-message build is inside the timed
//! `encode`.
//!
//! Author: aav
// --------------------------------------------------
// mods
// --------------------------------------------------
mod flat;
mod generated;
mod native;
mod nested;

// --------------------------------------------------
// local
// --------------------------------------------------
use crate::suite::Approach;

/// The micropb approach.
pub(crate) struct Micropb;

/// [`Micropb`] implementation of [`Approach`]
impl Approach for Micropb {
    const NAME: &'static str = "micropb";
}
