[package]
name = "tinyklv-impl"
version = "0.0.1-alpha.1"
authors = ["Arpad Voros <arpadav@gmail.com>"]
license = "MIT"
description = "Implementation detail of the `tinyklv` crate"
repository = "https://github.com/arpadav/tinyklv"
edition = "2021"
rust-version = "1.95"
publish = true

[lib]
proc-macro = true

[dependencies]
paste = "1.0"
quote = "1.0"
thiserror = "2.0"
proc-macro2 = "1.0"
tk-syn-macros = { path = "tk-syn-macros" }
syn = { version = "2.0", features = ["full", "extra-traits"] }

[dev-dependencies]

[features]
tracing = []
