[package]
name = "tinyklv"
version = "0.1.0"
authors = ["Arpad Voros <arpadav@gmail.com>"]
license = "MIT"
description = ""
repository = "https://github.com/arpadav/tinyklv"
documentation = "https://docs.rs/tinyklv"
readme = "README.md"
# keywords = ["enum", "const", "literals", "macro", "parsing"]
# categories = ["parsing", "memory-management"]
edition = "2021"

[dependencies]
nom = "7.1"
winnow = "0.6"
num-traits = "0.2"
tinyklv-impl = { version = "0.1", path = "impl" }
tinyklv-macros = { version = "0.1", path = "macros" }

[dev-dependencies]

[profile.dev]
opt-level = 0

[profile.release]
lto = true
strip = true
opt-level = 3
panic = "abort"
codegen-units = 1

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"