[package]
name = "tk-syn-macros"
version = "0.0.1"
edition = "2024"
description = "Implementation detail of the `tinyklv` crate"
documentation = "https://docs.rs/tinyklv"
homepage = "https://arpadvoros.com/tinyklv"
repository = "https://github.com/arpadav/tinyklv"
keywords = ["decode", "encode", "klv", "parsing", "tlv"]
categories = ["development-tools", "encoding", "parsing"]
publish = true

[dependencies]
paste = "^1.0"
quote = "^1.0"
syn = "^2.0"

[dev-dependencies]
const_format = "^0.2"
syn = { version = "^2.0", features = ["extra-traits", "full"] }
