//! Regenerates the committed `generated.rs` files for the four protobuf benchmark approaches.
//!
//! One binary, four codegen backends, driven from the shared schemas in `benches/proto/`. The
//! build machine needs no system `protoc`: prost-build and micropb-gen use the `protoc` binary
//! vendored by `protoc-bin-vendored`, while protobuf-codegen (rust-protobuf) and pb-rs
//! (quick-protobuf) parse `.proto` in pure Rust.
//!
//! Records (schemas live in `benches/proto/`; their basenames are the `*_PROTO` consts below and
//! are never re-spelled in prose):
//! * `Simple` and `Compound` (package `bench`) are generated for every backend.
//! * `Rich` (native types, package `bench_native`) has two variants: a well-known-type schema
//!   (google.protobuf timestamp/duration) feeds prost and rust_protobuf, which convert WKTs to
//!   `std::time`/chrono natively; a raw-integer-temporal schema feeds micropb and quick_protobuf,
//!   which have no such conversions.
//!
//! Each backend's output is normalised to one `benches/suite/approaches/<approach>/generated.rs`.
//!
//! Run directly (`cargo run --manifest-path benches/proto-gen/Cargo.toml`) or via
//! `benches/scripts/gencharts.sh -f`.
//!
//! Author: aav
// --------------------------------------------------
// external
// --------------------------------------------------
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use pb_rs::types::FileDescriptor;
use pb_rs::ConfigBuilder;

/// Header prepended to every generated file: a do-not-edit banner plus the inner `allow`
/// attribute that exempts the machine-written code from the crate's `clippy::pedantic = deny`.
const HEADER: &str = "\
// @generated by benches/proto-gen - DO NOT EDIT BY HAND.
// Regenerate with `benches/scripts/gencharts.sh -f` or by running the proto-gen crate directly.
#![allow(clippy::pedantic, clippy::all, unused, non_snake_case, non_camel_case_types)]
";

/// Schema basenames (no extension), the single source of truth for every `.proto` input path and
/// the per-file backend output (`<basename>.rs`) it reads back. Renaming a schema means editing
/// only the matching const here; nothing else in this file - or its docs - spells the name out.
const SIMPLE: &str = "simple";

/// See [`SIMPLE`].
const COMPOUND: &str = "compound";

/// The well-known-type `Rich` variant (prost / rust_protobuf). See [`SIMPLE`].
const RICH_WKT: &str = "rich_wkt";

/// The raw-scalar `Rich` variant (micropb / quick_protobuf). See [`SIMPLE`].
const RICH_RAW: &str = "rich";

/// The repo-relative paths every backend needs, resolved once and passed by reference.
struct Ctx {
    /// The `benches/proto` directory, the primary protoc include path.
    proto_dir: PathBuf,

    /// The two common inputs (the `Simple` and `Compound` schemas, package `bench`).
    common: Vec<PathBuf>,

    /// The WKT `Rich` variant for prost / rust_protobuf.
    native_wkt: PathBuf,

    /// The raw-scalar `Rich` variant for micropb / quick_protobuf.
    native_raw: PathBuf,

    /// The vendored `google/protobuf/*.proto` include path (for the WKT variant's imports).
    wkt_include: PathBuf,

    /// The vendored `protoc` binary, for the backends that shell out to it.
    protoc: PathBuf,

    /// A scratch directory each backend writes its raw output into.
    tmp: PathBuf,

    /// The `benches/suite/approaches` directory the `generated.rs` files land under.
    approaches: PathBuf,
}

fn main() {
    // --------------------------------------------------
    // resolve repo-relative paths from this crate's manifest dir
    // --------------------------------------------------
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let root = manifest
        .parent()
        .and_then(Path::parent)
        .expect("proto-gen lives at <root>/benches/proto-gen");
    let proto_dir = root.join("benches/proto");
    let ctx = Ctx {
        common: vec![
            proto_dir.join(format!("{SIMPLE}.proto")),
            proto_dir.join(format!("{COMPOUND}.proto")),
        ],
        native_wkt: proto_dir.join(format!("{RICH_WKT}.proto")),
        native_raw: proto_dir.join(format!("{RICH_RAW}.proto")),
        approaches: root.join("benches/suite/approaches"),
        protoc: protoc_bin_vendored::protoc_bin_path()
            .expect("vendored protoc binary (unsupported host triple?)"),
        wkt_include: protoc_bin_vendored::include_path().expect("vendored WKT include path"),
        tmp: env::temp_dir().join("tinyklv-proto-gen"),
        proto_dir,
    };

    gen_prost(&ctx);
    gen_rust_protobuf(&ctx);
    gen_quick_protobuf(&ctx);
    gen_micropb(&ctx);

    println!("proto-gen: wrote generated.rs for prost, rust_protobuf, quick_protobuf, micropb");
}

/// Writes `<approaches>/<approach>/generated.rs` with the do-not-edit [`HEADER`] prepended.
fn write_generated(approaches: &Path, approach: &str, body: &str) {
    let out = approaches.join(approach).join("generated.rs");
    fs::write(&out, format!("{HEADER}\n{body}")).expect("write generated.rs");
}

/// Reads one per-file backend output and wraps it in an inline `pub mod`, then re-exports it.
///
/// `reexport` selects what escapes the module: `None` re-exports everything (`pub use m::*`),
/// `Some(name)` re-exports only that item - used for the `native` module so its self-contained
/// `GpsCoord` copy does not collide with the `compound` module's `GpsCoord` at the top level.
fn wrap(dir: &Path, file: &str, module: &str, reexport: Option<&str>) -> String {
    let content = fs::read_to_string(dir.join(file)).expect("read backend output file");
    wrap_str(&content, module, reexport)
}

/// Wraps already-read source in an inline `pub mod` + re-export (the single home of the
/// module-wrap convention, shared by the file-based [`wrap`] and prost's in-memory combine).
fn wrap_str(content: &str, module: &str, reexport: Option<&str>) -> String {
    let re = match reexport {
        Some(name) => format!("pub use {module}::{name};"),
        None => format!("pub use {module}::*;"),
    };
    format!("pub mod {module} {{\n{content}\n}}\n{re}\n")
}

/// Creates and returns a fresh scratch sub-directory for one backend under [`Ctx::tmp`].
fn backend_dir(ctx: &Ctx, approach: &str) -> PathBuf {
    let dir = ctx.tmp.join(approach);
    fs::create_dir_all(&dir).expect("create backend tmp dir");
    dir
}

/// Generates prost: WKT variant. prost-build emits one file per package - `bench.rs` (Simple,
/// Compound, ...) and `bench_native.rs` (Rich) - which are combined here.
fn gen_prost(ctx: &Ctx) {
    let out_dir = backend_dir(ctx, "prost");
    let mut inputs = ctx.common.clone();
    inputs.push(ctx.native_wkt.clone());
    let mut cfg = prost_build::Config::new();
    cfg.out_dir(&out_dir);
    cfg.protoc_executable(&ctx.protoc);
    cfg.compile_protos(&inputs, &[&ctx.proto_dir, &ctx.wkt_include])
        .expect("prost compile_protos");
    let bench = fs::read_to_string(out_dir.join("bench.rs")).expect("read prost bench.rs");
    let native =
        fs::read_to_string(out_dir.join("bench_native.rs")).expect("read prost bench_native.rs");
    let body = format!(
        "{bench}\n{}",
        wrap_str(&native, "bench_native", Some("Rich"))
    );
    write_generated(&ctx.approaches, "prost", &body);
}

/// Generates rust-protobuf: WKT variant, pure parser (no protoc), per-file output stitched.
fn gen_rust_protobuf(ctx: &Ctx) {
    let out_dir = backend_dir(ctx, "rust_protobuf");
    let mut inputs = ctx.common.clone();
    inputs.push(ctx.native_wkt.clone());
    protobuf_codegen::Codegen::new()
        .pure()
        .include(&ctx.proto_dir)
        .include(&ctx.wkt_include)
        .inputs(&inputs)
        .out_dir(&out_dir)
        .run()
        .expect("protobuf-codegen run");
    let body = format!(
        "{}{}{}",
        wrap(&out_dir, &format!("{SIMPLE}.rs"), "simple", None),
        wrap(&out_dir, &format!("{COMPOUND}.rs"), "compound", None),
        wrap(&out_dir, &format!("{RICH_WKT}.rs"), "native", Some("Rich")),
    );
    write_generated(&ctx.approaches, "rust_protobuf", &body);
}

/// Generates quick-protobuf: raw variant via the pb-rs library (no protoc), per-file stitched.
fn gen_quick_protobuf(ctx: &Ctx) {
    let out_dir = backend_dir(ctx, "quick_protobuf");
    let mut inputs = ctx.common.clone();
    inputs.push(ctx.native_raw.clone());
    let includes = [ctx.proto_dir.clone()];
    let cfg = ConfigBuilder::new(&inputs, None, Some(&out_dir), &includes)
        .expect("pb-rs ConfigBuilder")
        .single_module(true)
        .dont_use_cow(true);
    FileDescriptor::run(&cfg.build()).expect("pb-rs run");
    let body = format!(
        "{}{}{}",
        wrap(&out_dir, &format!("{SIMPLE}.rs"), "simple", None),
        wrap(&out_dir, &format!("{COMPOUND}.rs"), "compound", None),
        wrap(&out_dir, &format!("{RICH_RAW}.rs"), "native", Some("Rich")),
    );
    write_generated(&ctx.approaches, "quick_protobuf", &body);
}

/// Generates micropb: raw variant, single file, alloc containers so `repeated`/`bytes` use `Vec`.
fn gen_micropb(ctx: &Ctx) {
    let out_dir = backend_dir(ctx, "micropb");
    let out_file = out_dir.join("generated.rs");
    let mut inputs = ctx.common.clone();
    inputs.push(ctx.native_raw.clone());
    // SAFETY: single-threaded codegen binary; no other thread reads the environment.
    unsafe { env::set_var("PROTOC", &ctx.protoc) };
    let mut generator = micropb_gen::Generator::new();
    generator.use_container_alloc();
    generator.add_protoc_arg("-I");
    generator.add_protoc_arg(&ctx.proto_dir);
    generator
        .compile_protos(&inputs, &out_file)
        .expect("micropb compile_protos");
    let body = fs::read_to_string(&out_file).expect("read micropb output");
    write_generated(&ctx.approaches, "micropb", &body);
}
