#!/usr/bin/env bash
# regenerate the README perf charts: regenerate the protobuf approach code, run the criterion
# suite bench, then render the two paradigm charts (bench_klv.jpg, bench_proto.jpg) from
# criterion's own results in target/criterion
#
# the chart is rendered on a log value axis: the `streamed` tier decodes STREAM_PACKETS packets
# per call, so its absolute time is ~64x a single value/frame decode - a linear axis would crush
# the smaller bars flat. log keeps every tier readable in one chart
#
# the matplotlib venv (benches/.venv, gitignored) is created automatically on
# first run; `uv` must be on PATH
#
# the protobuf `generated.rs` files are regenerated by the proto-gen helper crate on a forced
# run; it vendors its own `protoc` (via protoc-bin-vendored) and uses pure-Rust parsers, so no
# system `protoc` / `pb-rs` is required
#
# usage: benches/scripts/gencharts.sh [-o h|v] [-s log|lin] [-k bar|box] [-n abs|byte|pkt] [-f|--force]
#   -o, --orientation - chart orientation forwarded to plot_times.py (default h)
#   -s, --scale       - value-axis scale forwarded to plot_times.py (default lin)
#   -k, --kind        - bar vs box forwarded to plot_times.py (default bar)
#   -n, --norm        - abs/byte/pkt normalization forwarded to plot_times.py (default byte)
#   -f, --force       - regenerate the protobuf code and re-run the criterion bench even if results
#                       already exist; otherwise existing target/criterion results are reused and
#                       the script just re-renders the charts
#
# author: aav
set -euo pipefail
cd "$(dirname "$0")/../.."

# --------------------------------------------------
# print usage function
# --------------------------------------------------
usage() {
    echo "Usage: bash benches/scripts/gencharts.sh [-o|--orientation h|v] [-s|--scale log|lin] \
[-k|--kind bar|box] [-n|--norm abs|byte|pkt] [-f|--force]"
    echo "  forwards orientation/scale/kind/norm to plot_times.py; --force re-runs the criterion bench"
}

# --------------------------------------------------
# defaults (override with the flags below)
# --------------------------------------------------
ORIENTATION=h       # default groups on the y-axis (horizontal bars)
SCALE=lin           # default linear value axis
KIND=bar            # default median grouped bars (vs box-and-whisker)
NORM=byte           # default ns-per-input-byte normalization
FORCE=false         # default to reusing existing criterion results

# --------------------------------------------------
# parse cli args
# --------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
    -o | --orientation) ORIENTATION="$2"; shift 2 ;;
    -s | --scale)       SCALE="$2"; shift 2 ;;
    -k | --kind)        KIND="$2"; shift 2 ;;
    -n | --norm)        NORM="$2"; shift 2 ;;
    -f | --force)       FORCE=true; shift ;;
    -h | --help)        usage; exit 0 ;;
    *)                  echo "Unknown argument: $1"; usage; exit 1 ;;
    esac
done

# --------------------------------------------------
# constants
# --------------------------------------------------
CRITERION_DIR="target/criterion"
SENTINEL="$CRITERION_DIR/simple_decode_value/tinyklv/new/estimates.json"
VENV="benches/.venv"
PY="$VENV/bin/python"

# --------------------------------------------------
# bootstrap the plotting venv if it is missing
# --------------------------------------------------
if [[ ! -x "$PY" ]]; then
    echo "==> creating $VENV (matplotlib + numpy)"
    command -v uv >/dev/null || { echo "error: uv not found on PATH" >&2; exit 1; }
    uv venv "$VENV"
    uv pip install --python "$PY" matplotlib numpy
fi

# --------------------------------------------------
# run the criterion suite bench (skip if results exist and not forced)
# --------------------------------------------------
if [[ "$FORCE" == true || ! -f "$SENTINEL" ]]; then
    echo "==> regenerating protobuf approach code (proto-gen)"
    cargo run --quiet --manifest-path benches/proto-gen/Cargo.toml
    echo "==> running criterion suite bench"
    # --features bench enables tinyklv's native-type codecs (required by the suite)
    RUSTFLAGS='-C target-cpu=native' cargo bench --bench compsuite --features bench
else
    echo "==> reusing existing criterion results (pass -f to re-run)"
fi

# --------------------------------------------------
# render the two paradigm charts from criterion's medians (knobs from the cli args / defaults)
# --------------------------------------------------
echo "==> rendering charts ($ORIENTATION $SCALE $KIND $NORM)"
"$PY" benches/scripts/plot_times.py "$CRITERION_DIR" "$ORIENTATION" "$SCALE" "$KIND" "$NORM" benches
echo "==> done - images written to benches/bench_klv.jpg and benches/bench_proto.jpg"
